# Generated by Django 4.0.6 on 2022-07-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_mahsulot_olchov_alter_mahsulot_ichki'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='min_buyurtma',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
