# Generated by Django 4.0.6 on 2022-07-26 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_mahsulot_min_buyurtma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulot_rasmi', to='asosiy.mahsulot'),
        ),
    ]
