# Generated by Django 4.0.6 on 2022-07-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
