# Generated by Django 4.0.6 on 2022-07-26 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accaunt',
            new_name='Account',
        ),
    ]
